config/routes.rb
WwwSamplerailsappCom::Application.routes.draw do
 root :to => 'main#home'
  get "main/home"

  get "main/shop"

  get "main/deals"

  get "main/contact"

  match '/home',    to: 'main#home'
  match '/shop',    to: 'main#shop'
  match '/deals',   to: 'main#deals' 
  match '/contact',    to: 'main#contact'
  
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def shop
  end

  def deals
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav pull-right">
          <li><%= link_to "Home",root_path %></li>
          <li><%= link_to "Shop",shop_path %></li>
          <li><%= link_to "Deals",deals_path %></li>
          <li><%= link_to "Contact",contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer class="footer">
  <small>
    Copyright
  </small>
  <nav>
    <ul>
      <li><%= link_to "Deals",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
     </ul>
  </nav>
</footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/main/contact.html.erb
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

app/views/main/deals.html.erb
<h1>Main#deals</h1>
<p>Find me in app/views/main/deals.html.erb</p>

app/views/main/home.html.erb
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>

app/views/main/shop.html.erb
<h1>Main#shop</h1>
<p>Find me in app/views/main/shop.html.erb</p>